Repository RoboCup-SSL/ssl-rules, pull requests merged in 2020-02, with the labels that each got.

#5 Ball going out of field (due to chip kick) (both Div)
  chapters/offenses.adoc
Labels: DivA, DivB, release candidate

#6 Change Div A num robots to 11
  chapters/robots.adoc
Labels: DivA, release candidate

#7 Add rule for changing keeper Id
  chapters/gamestructure.adoc
  chapters/playingenvironment.adoc
Labels: DivA, DivB, release candidate

#9 Robot interchange during game play (Both Div)
  chapters/gamestructure.adoc
  chapters/playingenvironment.adoc
  chapters/substitution.adoc
Labels: DivA, DivB, release candidate

#10 Do not stop for cards (both Div)
  chapters/refereecommands.adoc
Labels: DivA, DivB, release candidate

#11 Emergency stop (Div A)
  chapters/emergencystop.adoc
  sslrules.adoc
Labels: DivA, release candidate

#12 Add rule for rule changes during competition
  chapters/rulechanges.adoc
  sslrules.adoc
Labels: DivA, DivB, release candidate

#14 Remove Penalty Kicks (both Div)
  chapters/playingenvironment.adoc
  chapters/refereecommands.adoc
  chapters/scoringgoals.adoc
  chapters/shootout.adoc
Labels: DivA, DivB, release candidate

#26 Communication flags (Both Div)
  chapters/playingenvironment.adoc
Labels: DivA, DivB, release candidate

#29 Resume at the location of the ball when play is stopped after foul
  chapters/offenses.adoc
Labels: DivA, DivB, release candidate

#28 Field drawings update for wall gameplay
  images/quad-size-field.svg
Labels: release candidate
