Repository RoboCup-SSL/ssl-rules, pull requests merged in 2020-03, with the labels that each got.

#3 Merge indirect and direct free kick into (direct) free kick
  chapters/appendix.adoc
  chapters/ballleavesthefield.adoc
  chapters/offenses.adoc
  chapters/refereecommands.adoc
  chapters/scoringgoals.adoc
Labels: DivA, DivB, feedback wanted, release candidate

#27 Challenge flag (Both Div)
  chapters/challengeflag.adoc
  sslrules.adoc
Labels: DivA, DivB, feedback wanted, release candidate

#31 Tune ball placement procedure
  chapters/refereecommands.adoc
Labels: DivA, DivB, release candidate

#30 Increase defense area and goal size
  chapters/playingenvironment.adoc
  images/goal_detail_divisionA.svg
  images/quad-size-field.svg
Labels: DivA, release candidate

#15 Multiple yellow cards turn into red cards instead of penalty kicks
  chapters/appendix.adoc
  chapters/refereecommands.adoc
Labels: DivA, DivB, release candidate

#32 Restructure fouls and offenses sections
  chapters/appendix.adoc
  chapters/ballleavesthefield.adoc
  chapters/challengeflag.adoc
  chapters/offenses.adoc
  chapters/playingenvironment.adoc
  chapters/refereecommands.adoc
  chapters/scoringgoals.adoc
  sslrules.adoc
Labels: DivA, DivB, release candidate, review wanted
